#!/usr/bin/env node
// Generates src/trustStore/generated/rootCerts.generated.ts from
// src/trustStore/roots/* (excludes *.md), so Cloudflare Workers -- no real
// filesystem at runtime -- still gets a working trust store baked in at
// build time. See roots/README.md.
//
// (Intermediate CAs are no longer bundled here -- certChainVerifier.ts
// discovers them dynamically per verify request via each certificate's own
// AIA `caIssuers` URL, see aiaCertFetcher.ts.)
//
// Regenerate manually: npm run gen:certs
// Also runs automatically via the npm `prebuild` lifecycle before every
// `npm run build` (the VPS's scripts/deploy.sh and Cloudflare's build both
// end up invoking `npm run build`).
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, 'src', 'trustStore', 'generated');
const TARGETS = [
  {
    dir: path.join(ROOT, 'src', 'trustStore', 'roots'),
    outFile: path.join(OUT_DIR, 'rootCerts.generated.ts'),
    exportName: 'generatedRootCerts',
  },
];

function buildManifest(dir) {
  // No try/catch here (unlike the runtime loader): a missing/unreadable
  // source directory at generation time is a real repo problem and should
  // fail the build loudly, not silently ship an empty manifest.
  return readdirSync(dir)
    .filter((f) => !f.toLowerCase().endsWith('.md'))
    .sort() // deterministic output regardless of OS/filesystem readdir order
    .map((filename) => ({
      filename,
      base64: readFileSync(path.join(dir, filename)).toString('base64'),
    }));
}

function emit({ dir, outFile, exportName }) {
  const entries = buildManifest(dir);
  const relDir = path.relative(ROOT, dir).replace(/\\/g, '/');
  const header = `// AUTO-GENERATED by scripts/generateCertManifest.js -- DO NOT HAND-EDIT.
// Regenerate: npm run gen:certs (also runs automatically before \`npm run build\`).
// Source: ${relDir} (excludes *.md)
import type { CertManifestEntry } from '../certBundleLoader';

export const ${exportName}: CertManifestEntry[] = `;
  writeFileSync(outFile, header + JSON.stringify(entries, null, 2) + ';\n');
  console.log(`[gen:certs] ${path.relative(ROOT, outFile)}: ${entries.length} file(s)`);
}

mkdirSync(OUT_DIR, { recursive: true });
for (const target of TARGETS) emit(target);
